import * as T from './assets/three.module.js';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const contentRoot=$('#content-source').content;
const source={
 about:$('#about',contentRoot).innerHTML,
 work:(()=>{const items=$$('#internship-projects .project',contentRoot).map(x=>x.outerHTML);return [items[2],items[1],items[0],...items.slice(3)]})(),
 analysis:$$('#market-analysis .analysis-grid>.card',contentRoot).map(x=>x.outerHTML),
 innovation:$$('#product-innovation .innovation-grid>.card',contentRoot).map(x=>x.outerHTML),
 leadership:$$('#leadership .grid-2>.card',contentRoot).map(x=>x.outerHTML),
 contact:$('#contact',contentRoot).outerHTML,
};
const names={'about':'About Me','internship-projects':'Internship Projects','market-analysis':'Market Analysis','product-innovation':'Product Innovation and Marketing','leadership':'Leadership Experience','contact':'Contact'};
const shortTitles=['Global Content Strategy','Audience Expansion','AI Marketing Ops','Luxury Event Execution','Product Marketing','TikTok Strategy'];
const intro=$('#source-intro',contentRoot).innerHTML;
const experience=$('#experience'),view=$('#view');
let previousFocus=null,globeCleanup=()=>{},activeView='',skillIndex=0,workIndex=-1,binderSelected=0,pageIndex=0,productIndex=0,leaderIndex=-1;
function disposeView(){globeCleanup();globeCleanup=()=>{}}
function clearDeskHover(){hovered=null;const label=$('#object-label');if(label)label.style.opacity=0;if($('#scene'))$('#scene').style.cursor='grab'}
function show(id){disposeView();clearDeskHover();previousFocus=document.activeElement;activeView=id;resetCamera();if(renderer&&camera&&scene){camera.position.copy(cameraGoal);currentLook.copy(lookGoal);camera.lookAt(currentLook);renderer.render(scene,camera)}experience.className='is-open view-'+id;experience.setAttribute('aria-hidden','false');$('#scene').classList.add('is-blurred');view.innerHTML='';({about:renderAbout,'internship-projects':renderWork,'market-analysis':renderNotebook,'product-innovation':renderProducts,leadership:renderLeadership,contact:renderContact}[id])();const closeButton=$('#close-view'),closeText=id==='internship-projects'?'Exit internship projects':'Close and return to desk';closeButton.setAttribute('aria-label',closeText);closeButton.title=closeText;closeButton.focus();}
function close(){disposeView();clearDeskHover();experience.className='';experience.setAttribute('aria-hidden','true');view.innerHTML='';$('#scene').classList.remove('is-blurred');resetCamera();previousFocus?.focus();}
$('#close-view').onclick=close;
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&experience.classList.contains('is-open'))close();if(activeView==='about'&&view.querySelector('.skills-stage')){if(e.key==='ArrowLeft')rotateSkills(-1);if(e.key==='ArrowRight')rotateSkills(1)}});
document.addEventListener('click',e=>{const b=e.target.closest('[data-open]');if(b)navigate(b.dataset.open);if(e.target.closest('[data-home]')){if(experience.classList.contains('is-open'))close();resetCamera();}});
function renderAbout(){const temp=document.createElement('div');temp.innerHTML=source.about;const about=$('.about-grid',temp);view.innerHTML='<div class="computer-view"><div class="computer-screen"><div class="computer-top"><img src="photos/selfie.JPG" alt="Portrait of Fanqi Xu"><div><h2>Fanqi (Fegga) Xu</h2></div></div><div class="about-panels">'+about.innerHTML+'</div><button class="skills-launch" id="explore-skills">Explore My Skills →</button></div></div>';$('#explore-skills').onclick=renderSkills;}
const skills=[
 ['Strategy',['Go-to-Market Strategy','Audience Strategy','Media Planning','Growth Strategy'],'0% 0%'],
 ['Analytics',['Performance Analysis','Funnel Analysis','A/B Testing','Market Insights'],'50% 0%'],
 ['Execution',['Campaign Execution','Content & Creative','Integrated Marketing Communication'],'100% 0%'],
 ['Languages',['Mandarin — Native','English — Fluent','IELTS 7.5'],'0% 100%'],
 ['Technical',['SQL','Excel','PowerPoint','SPSS','Adobe Creative Suite','Canva','CapCut'],'50% 100%'],
 ['AI & Automation',['Codex','Cursor','AI Agent Development','Workflow Automation','Vibe Coding','AI-Assisted Web Development'],'100% 100%']
];
function renderSkills(){view.innerHTML='<div class="skills-stage"><button class="subtle-return" id="skills-back">← Computer</button><div class="skill-arc" aria-label="Skill wheel">'+skills.map((s,i)=>'<button class="skill-card" data-skill="'+i+'" aria-label="'+s[0]+'" style="--pos:'+s[2]+'"><div class="skill-tomato" role="img" aria-label="'+s[0]+' tomato illustration"></div><div class="skill-details"><ul>'+s[1].map(x=>'<li>'+x+'</li>').join('')+'</ul></div></button>').join('')+'</div><div class="skill-arrows"><button id="skill-prev" aria-label="Rotate skills left">←</button><button id="skill-next" aria-label="Rotate skills right">→</button></div></div>';updateSkillWheel();$('#skills-back').onclick=renderAbout;$$('[data-skill]').forEach(b=>b.onclick=()=>{skillIndex=+b.dataset.skill;updateSkillWheel()});$('#skill-prev').onclick=()=>rotateSkills(-1);$('#skill-next').onclick=()=>rotateSkills(1);const arc=$('.skill-arc');let start=0,moved=0;arc.onpointerdown=e=>{start=e.clientX;moved=0;arc.setPointerCapture(e.pointerId)};arc.onpointermove=e=>{if(start){moved=e.clientX-start}};arc.onpointerup=()=>{if(Math.abs(moved)>35)rotateSkills(moved<0?1:-1);start=0};arc.onwheel=e=>{e.preventDefault();rotateSkills(e.deltaY>0||e.deltaX>0?1:-1)},{passive:false};}
function rotateSkills(delta){skillIndex=(skillIndex+delta+6)%6;updateSkillWheel()}
function updateSkillWheel(){const cards=$$('.skill-card');cards.forEach((card,i)=>{let d=(i-skillIndex+6)%6;if(d>3)d-=6;const angle=d*.43;const x=Math.sin(angle)*Math.min(innerWidth*.34,390);const y=115-Math.cos(angle)*175;const proximity=Math.max(0,1-Math.abs(d)/3);card.style.cssText+=';--x:'+x+'px;--y:'+y+'px;--scale:'+(0.66+proximity*.34)+';--rotate:'+(d*7)+'deg;--opacity:'+(0.42+proximity*.58)+';--z:'+(10-Math.abs(d));card.classList.toggle('is-active',d===0);card.setAttribute('aria-pressed',d===0)})}
function projectParts(i){const temp=document.createElement('div');temp.innerHTML=source.work[i];const project=$('.project',temp),copy=$('.project-copy',project),role=$('.role',copy),title=$('h3',copy),img=$('img',project);const media=[...project.children].find(x=>!x.classList.contains('project-copy'));const body=copy.cloneNode(true);$('.role',body)?.remove();$('h3',body)?.remove();return{role:role?.textContent||'',title:title?.textContent||shortTitles[i],img:img?.outerHTML||'',media:media?.innerHTML||'',body:body.innerHTML}}
function paperLayers(items,side){const start=side==='left'?0:3;return items.slice(start,start+3).map((p,j)=>{const i=start+j,dir=side==='left'?1:-1;return '<div class="page-layer '+side+' '+(i===binderSelected?'is-selected':'')+'" data-file="'+i+'" style="--offset:'+(dir*j*7)+'px;--layer:'+(j*6)+'px;--tilt:'+(side==='left'?-.35:.35)*(j+1)+'deg;--layer-z:'+(3-j)+';--tab-color:'+['#efd485','#aecad1','#d88972'][j]+';--tab-y:'+(8+j*40)+'%"><div class="paper-stub"><span class="sheet-teaser">'+p.img+'<strong>'+p.title+'</strong></span></div><button class="binder-index-tab '+side+'" title="Open '+shortTitles[i]+'" aria-label="Open '+shortTitles[i]+'">'+shortTitles[i]+'</button></div>'}).join('')}
function editorialSheet(p,i){return '<header class="sheet-header"><p class="role">'+p.role+'</p><h3>'+p.title+'</h3></header><div class="project-editorial '+(i%2?'is-reversed':'')+'"><div class="sheet-media '+(i===1?'phone-media':'')+'">'+p.media+'</div><div class="sheet-body">'+p.body+'</div></div>'}
function renderWork(){const items=source.work.map((_,i)=>projectParts(i));view.innerHTML='<div class="binder-stage">'+(workIndex>=0?'<button class="projects-back" title="Back to all internship projects" aria-label="Back to all internship projects">← Back to All Projects</button>':'')+'<div class="binder '+(workIndex>=0?'is-reading':'')+'"><div class="paper-stack left">'+paperLayers(items,'left')+'</div><div class="binder-rings">'+Array(5).fill('<i></i>').join('')+'</div><div class="paper-stack right">'+paperLayers(items,'right')+'</div><span class="binder-hint">Select a project tab</span></div>'+(workIndex>=0?'<article class="active-paper" style="--from-x:'+(workIndex<3?'-36vw':'36vw')+';--from-y:'+(18+(workIndex%3)*9)+'%">'+editorialSheet(items[workIndex],workIndex)+'</article>':'')+'</div>';$$('[data-file]').forEach(layer=>{layer.addEventListener('click',e=>{e.stopPropagation();extractPaper(+layer.dataset.file)});layer.addEventListener('focusin',()=>layer.classList.add('is-hovered'));layer.addEventListener('focusout',()=>layer.classList.remove('is-hovered'))});$('.binder-stage')?.addEventListener('click',e=>{if(workIndex>=0&&!e.target.closest('.active-paper')&&!e.target.closest('[data-file]')&&!e.target.closest('.projects-back'))returnPaper()});$('.projects-back')?.addEventListener('click',e=>{e.stopPropagation();returnPaper()});}
function returnPaper(next=null){const active=$('.active-paper');if(!active){if(next!==null){workIndex=next;binderSelected=next;renderWork()}return}active.classList.add('is-returning');setTimeout(()=>{workIndex=-1;if(next!==null){workIndex=next;binderSelected=next}renderWork()},reduced?0:520)}
function extractPaper(i){binderSelected=i;if(workIndex>=0){returnPaper(i);return}workIndex=i;renderWork()}
function analysisSpread(i){const temp=document.createElement('div');temp.innerHTML=source.analysis[i];return{left:$('.thumb',temp)?.innerHTML||'',right:'<p class="eyebrow">Research Notes · '+String(i+1).padStart(2,'0')+'</p>'+($('.copy',temp)?.innerHTML||'')}}
let noteTurning=false,noteDrag=null;
function setNotebookContent(i){const p=analysisSpread(i);$('.notebook-page.left').innerHTML=p.left;$('.notebook-page.right').innerHTML=p.right;$('.notebook-controls span').textContent=(i+1)+' / '+source.analysis.length;$('#page-prev').disabled=i===0;$('#page-next').disabled=i===source.analysis.length-1}
function renderNotebook(){view.innerHTML='<div class="notebook-stage"><div class="notebook" id="notebook"><div class="notebook-page left"></div><div class="notebook-page right"></div><div class="flip-sheet" id="flip-sheet"></div></div><div class="notebook-controls"><button id="page-prev" aria-label="Previous analysis">←</button><span></span><button id="page-next" aria-label="Next analysis">→</button></div></div>';setNotebookContent(pageIndex);$('#page-prev').onclick=()=>turnNotebook(-1);$('#page-next').onclick=()=>turnNotebook(1);const notebook=$('#notebook');notebook.onpointerdown=startNotebookDrag;notebook.onpointermove=moveNotebookDrag;notebook.onpointerup=endNotebookDrag;notebook.onpointercancel=endNotebookDrag;}
function prepareFlip(dir){const target=pageIndex+dir;if(target<0||target>=source.analysis.length)return null;const flip=$('#flip-sheet'),current=analysisSpread(pageIndex),next=analysisSpread(target),front=dir>0?current.right:current.left,back=dir>0?next.left:next.right;flip.className='flip-sheet '+(dir>0?'forward':'backward');flip.innerHTML='<div class="flip-face front">'+front+'</div><div class="flip-face back">'+back+'</div>';flip.style.transform='rotateY(0deg)';flip.style.boxShadow='none';if(dir>0){$('.notebook-page.right').innerHTML=next.right}else{$('.notebook-page.left').innerHTML=next.left}return{flip,target,dir}}
function flipFrames(dir,start=0,end=1){const sign=dir>0?-1:1,angle=p=>sign*p*180,skew=p=>Math.sin(p*Math.PI)*(dir>0?-3.2:3.2),shadow=p=>{const strength=Math.sin(p*Math.PI);return (dir>0?'-':'')+(12+strength*30)+'px 8px '+(20+strength*34)+'px rgba(58,54,43,'+(.1+strength*.22)+')'};const points=[start,Math.max(start,.18),Math.max(start,.48),Math.max(start,.76),end].filter((p,i,a)=>p<=end&&(i===0||p>a[i-1]));return points.map((p,i)=>({offset:points.length===1?1:(p-start)/(end-start||1),transform:'rotateY('+angle(p)+'deg) skewY('+skew(p)+'deg) translateZ('+(Math.sin(p*Math.PI)*8)+'px)',boxShadow:shadow(p),filter:'brightness('+(1-Math.sin(p*Math.PI)*.06)+')'}))}
function finishNotebookFlip(state){pageIndex=state.target;state.flip.className='flip-sheet';state.flip.innerHTML='';state.flip.removeAttribute('style');setNotebookContent(pageIndex);noteTurning=false;noteDrag=null}
function turnNotebook(dir){if(noteTurning)return;const state=prepareFlip(dir);if(!state)return;noteTurning=true;state.flip.animate(flipFrames(dir),{duration:reduced?0:1450,easing:'cubic-bezier(.34,.02,.18,1)',fill:'forwards'}).onfinish=()=>finishNotebookFlip(state)}
function startNotebookDrag(e){if(noteTurning||e.target.closest('button'))return;const rect=$('#notebook').getBoundingClientRect(),dir=e.clientX>rect.left+rect.width/2?1:-1,state=prepareFlip(dir);if(!state)return;noteTurning=true;noteDrag={...state,start:e.clientX,progress:0,pointer:e.pointerId};$('#notebook').setPointerCapture(e.pointerId)}
function moveNotebookDrag(e){if(!noteDrag||e.pointerId!==noteDrag.pointer)return;const width=$('#notebook').clientWidth/2,delta=(e.clientX-noteDrag.start)*(noteDrag.dir>0?-1:1);noteDrag.progress=Math.max(0,Math.min(1,delta/width));const p=noteDrag.progress,angle=noteDrag.dir*p*-180,strength=Math.sin(p*Math.PI);noteDrag.flip.style.transform='rotateY('+angle+'deg) skewY('+(strength*(noteDrag.dir>0?-3.2:3.2))+'deg) translateZ('+(strength*8)+'px)';noteDrag.flip.style.boxShadow=(noteDrag.dir>0?'-':'')+(12+strength*30)+'px 8px '+(20+strength*34)+'px rgba(58,54,43,'+(.1+strength*.22)+')';noteDrag.flip.style.filter='brightness('+(1-strength*.06)+')'}
function endNotebookDrag(e){if(!noteDrag||e.pointerId!==noteDrag.pointer)return;const d=noteDrag,complete=d.progress>.28,distance=complete?1-d.progress:d.progress,sign=d.dir>0?-1:1,strength=Math.sin(d.progress*Math.PI),frames=complete?flipFrames(d.dir,d.progress,1):[{transform:'rotateY('+(sign*d.progress*180)+'deg) skewY('+(strength*(d.dir>0?-3.2:3.2))+'deg)',boxShadow:d.flip.style.boxShadow},{transform:'rotateY(0deg) skewY(0deg)',boxShadow:'none',filter:'brightness(1)'}];d.flip.animate(frames,{duration:reduced?0:Math.max(360,1100*distance),easing:'cubic-bezier(.34,.02,.18,1)',fill:'forwards'}).onfinish=()=>{if(complete){finishNotebookFlip(d)}else{d.flip.className='flip-sheet';d.flip.innerHTML='';d.flip.removeAttribute('style');setNotebookContent(pageIndex);noteTurning=false;noteDrag=null}}}
function renderProducts(){view.innerHTML='<div class="product-stage"><div class="gift-base"></div><div class="product-carousel">'+source.innovation.map((html,i)=>{const d=document.createElement('div');d.innerHTML=html;return '<button class="product-preview" data-product="'+i+'">'+$('.thumb',d).innerHTML+$('h3',d).outerHTML+'</button>'}).join('')+'</div><div class="product-controls"><button id="product-prev" aria-label="Previous product">←</button><span></span><button id="product-next" aria-label="Next product">→</button></div></div>';updateProductCarousel();$$('[data-product]').forEach(b=>b.onclick=()=>{const i=+b.dataset.product;if(i===productIndex)openProductCase();else{productIndex=i;updateProductCarousel()}});$('#product-prev').onclick=()=>{productIndex=(productIndex+source.innovation.length-1)%source.innovation.length;updateProductCarousel()};$('#product-next').onclick=()=>{productIndex=(productIndex+1)%source.innovation.length;updateProductCarousel()};swipe($('.product-carousel'),()=>$('#product-next').click(),()=>$('#product-prev').click())}
function updateProductCarousel(){$$('[data-product]').forEach((card,i)=>{let d=i-productIndex;if(d>1)d-=source.innovation.length;if(d<-1)d+=source.innovation.length;const cfg=d===0?['0px','130px','0deg','1','1','3']:d<0?['-31vw','-80px','18deg','.78','.64','1']:['31vw','-80px','-18deg','.78','.64','1'];card.style.cssText='--x:'+cfg[0]+';--z:'+cfg[1]+';--ry:'+cfg[2]+';--s:'+cfg[3]+';--opacity:'+cfg[4]+';--zi:'+cfg[5];card.classList.toggle('is-active',d===0)});$('.product-controls span').textContent=(productIndex+1)+' / '+source.innovation.length}
function openProductCase(){const stage=$('.product-stage');stage.classList.add('is-expanded');stage.insertAdjacentHTML('beforeend','<article class="product-case"><button class="case-return">← BACK</button>'+source.innovation[productIndex]+'</article>');$('.case-return').onclick=()=>{$('.product-case')?.remove();stage.classList.remove('is-expanded')}}
function renderLeadership(){view.innerHTML='<div class="leadership-stage"><div class="globe-space"><div class="leadership-globe" id="lead-globe"></div><div class="pin-buttons"><button data-leader="0">Youth Fun</button><button data-leader="1">Student Union</button></div><p class="globe-caption">Drag the globe · Select a marker</p></div><article class="passport" id="passport">'+(leaderIndex>=0?source.leadership[leaderIndex]:'')+'</article></div>';function select(i){leaderIndex=i;$('#passport').innerHTML=source.leadership[i];$$('[data-leader]').forEach(b=>b.setAttribute('aria-selected',+b.dataset.leader===i));if(globeControl)globeControl.target=i===0?-.5:1.1}let globeControl=null;$$('[data-leader]').forEach(b=>b.onclick=()=>select(+b.dataset.leader));try{globeControl=makeGlobe($('#lead-globe'),select);globeCleanup=globeControl.dispose}catch(e){$('#lead-globe').textContent='Select an experience marker.'}if(leaderIndex>=0)select(leaderIndex)}
function renderContact(){view.innerHTML='<div class="sticky-contact">'+source.contact+'</div>'}
function swipe(el,next,prev){let x=0,y=0;el.addEventListener('pointerdown',e=>{x=e.clientX;y=e.clientY});el.addEventListener('pointerup',e=>{if(Math.abs(e.clientX-x)>55&&Math.abs(e.clientY-y)<70)(e.clientX<x?next:prev)()})}
const lightbox=$('#lightbox');document.addEventListener('click',e=>{if(e.target.tagName==='IMG'&&!lightbox.contains(e.target)&&!e.target.closest('button')){const img=$('img',lightbox);img.src=e.target.src;img.alt=e.target.alt;lightbox.showModal()}});$('button',lightbox).onclick=()=>lightbox.close();lightbox.onclick=e=>{if(e.target===lightbox)lightbox.close()};
document.addEventListener('error',e=>{if(e.target instanceof HTMLImageElement){e.target.hidden=true;e.target.closest('figure')?.classList.add('image-unavailable')}},true);
const particleCanvas=$('#particle-layer'),particleCtx=particleCanvas.getContext('2d'),particles=[];let particleLast={x:innerWidth/2,y:innerHeight/2,t:0},particleRaf=0;
function sizeParticles(){const d=Math.min(devicePixelRatio,2);particleCanvas.width=innerWidth*d;particleCanvas.height=innerHeight*d;particleCanvas.style.width=innerWidth+'px';particleCanvas.style.height=innerHeight+'px';particleCtx.setTransform(d,0,0,d,0,0)}
function addTrail(e){if(reduced||e.pointerType==='touch')return;const now=performance.now(),dx=e.clientX-particleLast.x,dy=e.clientY-particleLast.y,dist=Math.hypot(dx,dy),dt=Math.max(8,now-particleLast.t),speed=dist/dt,count=Math.min(innerWidth<700?2:5,Math.max(1,Math.round(1+speed*2.6)));for(let i=0;i<count;i++){const life=460+Math.random()*560,back=Math.random();particles.push({x:e.clientX-dx*back+(Math.random()-.5)*12,y:e.clientY-dy*back+(Math.random()-.5)*12,vx:-dx*.018+(Math.random()-.5)*.45,vy:-dy*.018-.12-Math.random()*.3,r:1.3+Math.random()*(speed>1?3.6:2.5),life,age:0,color:['201,105,75','231,194,93','137,157,109','145,184,192'][Math.floor(Math.random()*4)]})}particleLast={x:e.clientX,y:e.clientY,t:now};if(!particleRaf)particleRaf=requestAnimationFrame(drawTrail)}
function drawTrail(t){particleCtx.clearRect(0,0,innerWidth,innerHeight);for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.age+=16;if(p.age>=p.life){particles.splice(i,1);continue}p.x+=p.vx;p.y+=p.vy;p.vy-=.002;const a=(1-p.age/p.life)*.32;particleCtx.beginPath();particleCtx.fillStyle='rgba('+p.color+','+a+')';particleCtx.shadowColor='rgba('+p.color+','+(a*.5)+')';particleCtx.shadowBlur=6;particleCtx.arc(p.x,p.y,p.r*(1-p.age/p.life*.35),0,Math.PI*2);particleCtx.fill()}particleCtx.shadowBlur=0;particleRaf=particles.length?requestAnimationFrame(drawTrail):0}
sizeParticles();addEventListener('resize',sizeParticles);document.addEventListener('pointermove',addTrail,{passive:true});
// The desktop is real WebGL geometry; the content beneath it remains regular HTML.
const mat=(c,roughness=.65)=>new T.MeshStandardMaterial({color:c,roughness});
const cream=mat('#e9e3d2',.88),blue=mat('#91b8c0',.93),wood=mat('#a97853',.82),dark=mat('#35433b',.84),red=mat('#bf6753',.86),green=mat('#78936f',.94),yellow=mat('#e9c969',.9);
function box(w,h,d,m,x=0,y=0,z=0,parent){const mesh=new T.Mesh(new T.BoxGeometry(w,h,d),m);mesh.position.set(x,y,z);mesh.castShadow=true;mesh.receiveShadow=true;parent?.add(mesh);return mesh}
function cylinder(r1,r2,h,m,x,y,z,parent){const mesh=new T.Mesh(new T.CylinderGeometry(r1,r2,h,40),m);mesh.position.set(x,y,z);mesh.castShadow=true;mesh.receiveShadow=true;parent.add(mesh);return mesh}
function sphere(r,m,x,y,z,parent){const mesh=new T.Mesh(new T.SphereGeometry(r,40,24),m);mesh.position.set(x,y,z);mesh.castShadow=true;parent.add(mesh);return mesh}
function torus(r,t,m,x,y,z,parent){const mesh=new T.Mesh(new T.TorusGeometry(r,t,12,64),m);mesh.position.set(x,y,z);parent.add(mesh);return mesh}
function label(text,color='#394b40',bg='#e9e5d2',w=512,h=160){const c=document.createElement('canvas');c.width=w;c.height=h;const ctx=c.getContext('2d');ctx.fillStyle=bg;ctx.fillRect(0,0,w,h);ctx.fillStyle=color;ctx.font='bold '+Math.round(h*.3)+'px Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,w/2,h/2,w*.9);return new T.CanvasTexture(c)}
function planeText(text,w,h,x,y,z,parent,color,bg){const m=new T.MeshBasicMaterial({map:label(text,color,bg),side:T.DoubleSide});const mesh=new T.Mesh(new T.PlaneGeometry(w,h),m);mesh.position.set(x,y,z);parent.add(mesh);return mesh}
function globeBall(parent,r=.75){const g=new T.Group();parent.add(g);sphere(r,blue,0,0,0,g);for(let i=0;i<6;i++){let ring=torus(r+.006,.005,cream,0,0,0,g);ring.rotation.y=i*Math.PI/6;}for(let lat of [-.55,0,.55]){let ring=torus(Math.sqrt(r*r-lat*lat),.005,cream,0,lat,0,g);ring.rotation.x=Math.PI/2;}for(const [x,y,z,s] of [[-.32,.25,.59,.27],[.25,-.15,.63,.25],[.42,.4,-.34,.25],[-.5,-.3,-.35,.3]]){const land=sphere(s,green,x,y,z,g);land.scale.set(1,.8,.25);land.lookAt(new T.Vector3(x,y,z).multiplyScalar(2));}return g;}
let renderer,scene,camera,deskRoot,objects={},hovered=null,baseCamera=new T.Vector3(8.5,7.4,11.4),cameraGoal=baseCamera.clone(),lookGoal=new T.Vector3(0,.9,0),currentLook=lookGoal.clone(),sceneActive=true,opening=false,zoomFactor=1;
function resetCamera(){cameraGoal.copy(baseCamera).multiplyScalar(zoomFactor);lookGoal.set(0,.9,0);opening=false;}
function navigate(id){if(opening)return;if(experience.classList.contains('is-open')){show(id);return}if(!camera||!objects[id]||!sceneActive){show(id);return}opening=true;const p=new T.Vector3();objects[id].getWorldPosition(p);lookGoal.copy(p);cameraGoal.copy(p).add(new T.Vector3(2.35,2.2,4.1));objects[id].userData.open=true;setTimeout(()=>{show(id);opening=false;objects[id].userData.open=false},reduced?0:520);}
try{const host=$('#scene');scene=new T.Scene();camera=new T.PerspectiveCamera(34,1,.1,100);camera.position.copy(baseCamera);renderer=new T.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.setClearColor(0,0);host.append(renderer.domElement);$('#scene-status').remove();scene.add(new T.HemisphereLight('#fff9e7','#ada488',2.8));const light=new T.DirectionalLight('#fff1d2',4);light.position.set(-4,12,7);light.castShadow=true;light.shadow.mapSize.set(2048,2048);Object.assign(light.shadow.camera,{left:-12,right:12,top:12,bottom:-12});light.shadow.bias=-.0002;scene.add(light);deskRoot=new T.Group();scene.add(deskRoot);
 const ground=new T.Mesh(new T.PlaneGeometry(200,200),new T.ShadowMaterial({opacity:.11}));ground.rotation.x=-Math.PI/2;ground.position.y=-2.25;ground.receiveShadow=true;scene.add(ground);
 box(11,.22,5,blue,0,0,0,deskRoot);for(const x of [-4.8,4.8])for(const z of [-1.9,1.9])box(.23,2.2,.23,wood,x,-1.15,z,deskRoot);box(9.5,.2,.15,wood,0,-1.6,-1.9,deskRoot);
 function object(id,x,z){const g=new T.Group();g.position.set(x,.14,z);g.userData.id=id;g.userData.base=.14;deskRoot.add(g);objects[id]=g;return g}
 const pc=object('about',-.55,-.9);box(2.05,1.7,.65,cream,0,1.24,0,pc);box(1.7,1.23,.08,dark,0,1.34,.36,pc);planeText('Welcome to Fegga\'s Portfolio',1.53,.5,0,1.35,.408,pc,'#bfd8b0','#35433b');box(.65,.45,.5,cream,0,.35,0,pc);box(1.4,.14,.75,cream,0,.1,.15,pc);sphere(.045,green,.72,.58,.35,pc);const kb=box(1.95,.09,.68,cream,0,.1,1.35,pc);for(let r=0;r<3;r++)for(let c=0;c<12;c++)box(.12,.045,.11,mat('#bcbca9'),-.82+c*.145,.17,1.12+r*.17,pc);
 const folders=object('internship-projects',-3.3,.7),folderCoral=mat('#cf7f62',.9),folderGold=mat('#e6bd67',.92);folders.rotation.y=-.16;box(2.12,.07,1.52,folderCoral,0,.08,0,folders);box(1.92,.035,1.34,cream,.05,.135,.04,folders);const folderCover=box(2.12,.055,1.52,folderGold,0,.21,-.08,folders);folderCover.rotation.x=-.08;box(.72,.055,.28,folderGold,-.62,.22,-.88,folders);const ft=planeText('INTERNSHIP FILES',1.28,.25,.18,.255,-.18,folders,'#6b4936','#e6bd67');ft.rotation.x=-Math.PI/2;
 const gb=object('leadership',2.25,-1);cylinder(.52,.62,.11,cream,0,.05,0,gb);cylinder(.055,.055,.4,wood,0,.28,0,gb);const globe=globeBall(gb,.67);globe.position.y=1.13;globe.rotation.z=.2;const rim=torus(.79,.025,wood,0,1.13,0,gb);rim.rotation.y=.3;gb.userData.spin=globe;
 const book=object('market-analysis',1.3,1.2);book.rotation.y=-.25;box(1.25,.055,1.7,green,0,.055,0,book);box(1.13,.04,1.56,cream,.025,.105,0,book);box(1.25,.035,1.7,green,0,.145,0,book);const bp=planeText('FIELD NOTES',1,.3,0,.17,-.15,book,'#f1e9cf','#80996c');bp.rotation.x=-Math.PI/2;for(let i=0;i<7;i++){const ring=torus(.06,.014,dark,-.6,.18,-.62+i*.2,book);ring.rotation.y=Math.PI/2;}
 const gift=object('product-innovation',4,.1);box(1.05,.85,1.1,red,0,.48,0,gift);const lid=box(1.15,.14,1.2,cream,0,.96,0,gift);box(.18,.86,1.115,cream,0,.48,0,gift);gift.userData.lid=lid;const top=planeText('IDEAS',.8,.3,0,1.04,0,gift,'#b94836','#e9e5d2');top.rotation.x=-Math.PI/2;
 const note=object('contact',3.3,1.65);note.rotation.y=.15;box(1.1,.025,.95,yellow,0,.04,0,note);const np=planeText('LET’S TALK',.94,.32,0,.06,0,note,'#59482f','#e9c969');np.rotation.x=-Math.PI/2;
 const cup=new T.Group();cup.position.set(-2,.15,-1.1);deskRoot.add(cup);cylinder(.25,.2,.55,red,0,.28,0,cup);cylinder(.215,.215,.02,dark,0,.56,0,cup);const handle=torus(.18,.045,red,.28,.32,0,cup);handle.rotation.y=Math.PI/2;
 const plant=new T.Group();plant.position.set(-4.4,.15,-1.15);deskRoot.add(plant);cylinder(.29,.2,.45,cream,0,.23,0,plant);for(let i=0;i<6;i++){const leaf=sphere(.19,green,Math.cos(i)*.15,.62+(i%2)*.2,Math.sin(i)*.15,plant);leaf.scale.set(.5,2,.6);leaf.rotation.z=(i-2.5)*.2;}
 const pencil=new T.Group();pencil.position.set(.1,.22,1.4);pencil.rotation.set(Math.PI/2,0,.3);deskRoot.add(pencil);const pencilBody=cylinder(.06,.06,1.12,mat('#c94f43',.72),0,0,0,pencil);pencilBody.geometry=new T.CylinderGeometry(.06,.06,1.12,6);const woodTip=cylinder(0,.068,.22,mat('#d9b17a',.8),0,.67,0,pencil);woodTip.geometry=new T.ConeGeometry(.068,.22,6);const graphite=cylinder(0,.028,.075,dark,0,.815,0,pencil);graphite.geometry=new T.ConeGeometry(.028,.075,6);cylinder(.062,.062,.11,mat('#d9b17a',.65),0,-.615,0,pencil);cylinder(.064,.064,.1,mat('#d96f72',.72),0,-.72,0,pencil);
 const ray=new T.Raycaster(),pointer=new T.Vector2(),pointers=new Map();let down=null,dragged=false,pinch=null,deskYaw=deskRoot.rotation.y,deskPitch=deskRoot.rotation.x;
 function updateHover(e){const rect=host.getBoundingClientRect();pointer.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);ray.setFromCamera(pointer,camera);const hit=ray.intersectObjects(Object.values(objects),true)[0];let obj=hit?.object;while(obj&&!obj.userData.id)obj=obj.parent;hovered=obj||null;host.style.cursor=hovered?'pointer':down?'grabbing':'grab';const l=$('#object-label');l.style.opacity=hovered&&!dragged?'1':'0';if(hovered){l.textContent=names[hovered.userData.id];l.style.left=Math.min(rect.width-190,e.clientX-rect.left+12)+'px';l.style.top=e.clientY-rect.top-35+'px'}}
 function pinchDistance(){const a=[...pointers.values()];return a.length>1?Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y):0}
 host.addEventListener('pointerdown',e=>{updateHover(e);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});host.setPointerCapture(e.pointerId);if(pointers.size===2){pinch={distance:pinchDistance(),zoom:zoomFactor};down=null;dragged=true}else{down={x:e.clientX,y:e.clientY,yaw:deskYaw,pitch:deskPitch,lastX:e.clientX,lastY:e.clientY,lastTime:performance.now(),vx:0,vy:0};dragged=false}});
 host.addEventListener('pointermove',e=>{if(pointers.has(e.pointerId))pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size>1&&pinch){const distance=pinchDistance();zoomFactor=T.MathUtils.clamp(pinch.zoom*pinch.distance/Math.max(distance,1),.72,1.4);if(!opening)resetCamera();dragged=true}else if(down){const dx=e.clientX-down.x,dy=e.clientY-down.y;if(Math.hypot(dx,dy)>5){const now=performance.now(),dt=Math.max(8,now-down.lastTime);dragged=true;deskYaw=T.MathUtils.clamp(down.yaw+dx*.004,-.8,.8);deskPitch=T.MathUtils.clamp(down.pitch+dy*.0032,-.2,.3);down.vx=(e.clientX-down.lastX)/dt;down.vy=(e.clientY-down.lastY)/dt;down.lastX=e.clientX;down.lastY=e.clientY;down.lastTime=now}}updateHover(e)});
 host.addEventListener('pointerup',e=>{if(!dragged){updateHover(e);const target=hovered;if(target){clearDeskHover();navigate(target.userData.id)}}else if(down){deskYaw=T.MathUtils.clamp(deskYaw+down.vx*.055,-.8,.8);deskPitch=T.MathUtils.clamp(deskPitch+down.vy*.04,-.2,.3)}pointers.delete(e.pointerId);if(pointers.size<2)pinch=null;down=null});host.addEventListener('pointercancel',e=>{pointers.delete(e.pointerId);pinch=null;down=null});host.addEventListener('pointerleave',()=>{if(!pointers.size){down=null;clearDeskHover()}});host.addEventListener('wheel',e=>{e.preventDefault();zoomFactor=T.MathUtils.clamp(zoomFactor+e.deltaY*.00075,.72,1.4);if(!opening)resetCamera()},{passive:false});
 const resize=()=>{camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix();renderer.setSize(host.clientWidth,host.clientHeight);if(host.clientWidth<700){baseCamera.set(12.5,12.5,18.5);deskRoot.scale.setScalar(1.14)}else if(host.clientWidth<1100){baseCamera.set(9.2,8.2,13.2);deskRoot.scale.setScalar(1.1)}else{baseCamera.set(8.5,7.4,11.4);deskRoot.scale.setScalar(1.14)}if(!opening)resetCamera()};new ResizeObserver(resize).observe(host);resize();
 function frame(){requestAnimationFrame(frame);if(!sceneActive||document.hidden||experience.classList.contains('is-open'))return;camera.position.lerp(cameraGoal,reduced?1:.13);currentLook.lerp(lookGoal,reduced?1:.13);camera.lookAt(currentLook);deskRoot.rotation.y=T.MathUtils.lerp(deskRoot.rotation.y,deskYaw,reduced?1:.14);deskRoot.rotation.x=T.MathUtils.lerp(deskRoot.rotation.x,deskPitch,reduced?1:.14);for(const o of Object.values(objects)){const active=o===hovered&&!reduced;o.position.y=T.MathUtils.lerp(o.position.y,active?.28:.14,.15);const targetScale=active?1.055:1;o.scale.lerp(new T.Vector3(targetScale,targetScale,targetScale),.16);if(o.userData.spin&&active)o.userData.spin.rotation.y+=.012;if(o.userData.lid)o.userData.lid.position.y=T.MathUtils.lerp(o.userData.lid.position.y,o.userData.open?1.7:.96,.15);}renderer.render(scene,camera);}frame();
}catch(e){console.error(e);$('#scene-status').textContent='Explore the desk using the section buttons below.'}
function makeGlobe(host,onSelect){const r=new T.WebGLRenderer({alpha:true,antialias:true});r.setPixelRatio(Math.min(devicePixelRatio,1.5));r.shadowMap.enabled=true;host.append(r.domElement);const s=new T.Scene(),c=new T.PerspectiveCamera(34,1,.1,50);c.position.set(0,.2,4.5);s.add(new T.HemisphereLight('#fff8e4','#667d74',3.2));const l=new T.DirectionalLight('#fff0cf',2.5);l.position.set(-2,4,5);s.add(l);const stand=new T.Group();s.add(stand);cylinder(.72,.88,.14,cream,0,-1.15,0,stand);cylinder(.07,.07,.45,wood,0,-.93,0,stand);const ball=globeBall(stand,.84);ball.rotation.z=.13;const rim=torus(1,.025,wood,0,0,0,stand);rim.rotation.y=.25;const markers=[];['Youth Fun','Student Union'].forEach((name,i)=>{const a=i===0?.45:-1.1;const pin=sphere(.065,red,Math.sin(a)*.82,.24,Math.cos(a)*.82,ball);pin.userData.index=i;markers.push(pin);const tag=planeText(name,.72,.22,pin.position.x,pin.position.y+.2,pin.position.z+.07,ball,'#ffffff','#b95643');tag.userData.index=i;markers.push(tag)});let drag=null,live=true,raf;const control={target:0,dispose(){live=false;cancelAnimationFrame(raf);ro.disconnect();r.dispose();s.traverse(o=>{o.geometry?.dispose();if(o.material?.map)o.material.map.dispose();o.material?.dispose?.()});r.domElement.remove()}};const ro=new ResizeObserver(()=>{r.setSize(host.clientWidth,host.clientHeight);c.aspect=host.clientWidth/host.clientHeight;c.updateProjectionMatrix();r.setSize(host.clientWidth,host.clientHeight)});ro.observe(host);host.onpointerdown=e=>{drag={x:e.clientX,r:ball.rotation.y};host.setPointerCapture(e.pointerId)};host.onpointermove=e=>{if(drag){control.target=drag.r+(e.clientX-drag.x)*.01;ball.rotation.y=control.target}};host.onpointerup=e=>{if(drag&&Math.abs(e.clientX-drag.x)<8){const rect=host.getBoundingClientRect(),ray=new T.Raycaster();ray.setFromCamera(new T.Vector2((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1),c);const hit=ray.intersectObjects(markers)[0];if(hit)onSelect(hit.object.userData.index)}drag=null};function tick(){if(!live)return;raf=requestAnimationFrame(tick);if(!drag)ball.rotation.y=T.MathUtils.lerp(ball.rotation.y,control.target,reduced?1:.06);r.render(s,c)}tick();return control;}
